version: '3.8' 
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"

  test:
    build:
      context: .
      dockerfile: Dockerfile 
    command: npm test 
    depends_on:
      - web